### PR TITLE
Added missing memory usage field descriptions

### PR DESCRIPTION
**Pull request by amstelchen**
I checked all entries that come from /proc/meminfo whether they have meaningful descriptions in https://docs.kernel.org/filesystems/proc.html

### CODE REVIEW

**Comment by hwspeedy** [comment]
@amstelchen 
Very nice - Can we shorten the descriptions - they are too wide for the app.

Maybe change the description field to have a specific size and show all in a ballon text, when mouse hovers above the line?

We could make the app size bigger, but as it is also used on small SBC with a direct attached TFT - above 1024 could be less usable to some users...

Or another solution...

original
new_long_text

**Comment by amstelchen** [comment]
I don't know how, but either making the "Description" field smaller (probably easy to do) or resizable (probably a much bigger change in the codebase) would be also doable.

**Comment by hwspeedy** [comment]
Maybe remove the field part also - the description is the user friendly text.

But making the descriptions more compact are probably needed anyway as it requires a FullHD screen to show it with the original descriptions from kernel doc.

Sorting also seams to be missing...

PS: The description field is resizable to content, that is why the numbers are missing at app size 1024x800.

**Comment by amstelchen** [comment]
> Maybe remove the field part also - the description is the user friendly text.

But removing the kernel-provided field would remove an essential part of the provided information - ff I understood you correctly.

**Comment by hwspeedy** [comment]
Well for us that uses the kernel provided fields - yes. 
But maybe not so much for the users of the app - the explanation and value is giving insight of the system. That then cannot be correlated to a cat /proc/meminfo, when the field names are removed. 

PS: It is just removing it from app form (Not showing it) - not from list, where it still is needed to match read text from /proc/meminfo.

Try reducing the descriptions for all the longer text and lets see where we are.

tooLongText_Numbers_Missing

**Comment by hwspeedy** [comment]
Example of shorting description:
Anonymous memory that has been used more recently and usually not swapped out => **Anonymous memory actively used**

Not commonly swapped out to disc is maybe not be clear to anyone, but then they also do not know what anonymous memory is. So Give as much info that helps the users and create starting words for good sorting.

**Comment by amstelchen** [comment]
changes

**Comment by hwspeedy** [comment]
This is how the second change looks - much better - but still no numbers.
There is still a space in front of Field=Writeback

shorter_but_still_missing_a_solution

**Comment by hwspeedy** [comment]
Attached patch that removes the kernel memory field names from UI and sorts the memory usage information. 
Along with a picture of the outcome. One solution - If you have better please submit either way, thanx.

MemUse_fixup
[MemUsage_fixup.patch](https://github.com/hardinfo2/hardinfo2/files/14806930/MemUsage_fixup.patch)

**Pull request merged**
