### PR TITLE
Fix detection of Development entries

### PR DESCRIPTION
**Pull request by topazus**
```bash
hardinfo2 on  fix-perl6 via △ v3.28.3 took 4s 
❯ perl6 -v
Welcome to Rakudo™ v2024.07.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2024.07.

hardinfo2 on  fix-perl6 via △ v3.28.3 
❯ rakudo -v
Welcome to Rakudo™ v2024.07.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2024.07.

```

### CODE REVIEW

**Comment by topazus** [comment]
image
image

**Comment by topazus** [comment]
Gambas3 (gbr3) showed in the section of scripting languages and compilers. Maybe it will be fine to delete its appearance in the section of compilers?

**Comment by hwspeedy** [comment]
There is only one gbr3 --version, the other are gbc3 and gambas3. Are any of them following each others version since you call it duplet?

**Comment by topazus** [comment]
> There is only one gbr3 --version, the other are gbc3 and gambas3. Are any of them following each others version since you call it duplet?

Oh, I misread them, lol.

**Comment by hwspeedy** [comment]
good job with the tool versions - looks better here too.

**Pull request merged**
