### PR TITLE
Adding Hungarian translation

### PR DESCRIPTION
**Pull request by ViBE-HU**
I just realized that somehow the program now does not read .mo files if I just manually add it. So I cannot test atm.

### CODE REVIEW

**Comment by hwspeedy** [comment]
Thanx for starting the Hungarian translation, good work!

Have you tried building the hardinfo2 app and installing the package. That should work. If you are normally on an English language installation - I have seen that it was necessary to do a reboot.

For build and installation instructions please see - https://github.com/hardinfo2/hardinfo2/blob/master/README.md

**Comment by ViBE-HU** [comment]
@hwspeedy yes. Because I wanted to test on 24.04 so I had to. After my pull accepted I did another build and sadly something still wrong. It does not check/use the language file. The old program (HardInfo) directly reads locale folder content as most GTK programs do. It is a freshly installed system.

**Comment by hwspeedy** [comment]
@ViBE-HU - I see the same results - translations not working in Debian, but ok in Arch.

The locale dir was not found correctly and was hardcoded. I have added binreloc support and locale dir from build paths, along with actually allowing to disable binreloc and changed pot to hardinfo2.

I now have translations in Debian - but it needs more testing.

**Comment by ViBE-HU** [comment]
@hwspeedy just did a build from the unstable on 24.04. I can confirm that it's working now. Thanks for the fast fix.

**Pull request merged**
