### PR TITLE
FIX minor SVG improvements

### PR DESCRIPTION
**Pull request by tutralex**

### CODE REVIEW

**Comment by hwspeedy** [comment]
**media-removable.svg**

Nice, would some colors on the last black part of "sd/usb flash" be better?

Inspiration: https://cdn.icon-icons.com/icons2/1502/PNG/512/mediaremovable_103542.png

**Comment by tutralex** [comment]
@hwspeedy 
Ok, I'll redo this icon tomorrow.

**Comment by tutralex** [comment]
@hwspeedy 
"media-removable.svg" - fixed.

**Comment by hwspeedy** [comment]
Looks amazing, very nice.

**Pull request merged**
